# Pour Biome:
BIOME_NAME_LEN_MIN = 3
BIOME_NAME_LEN_MAX = 32
BIOME_PLUVIOMETRY_MIN = -4
BIOME_PLUVIOMETRY_MAX = 4
BIOME_TEMPERATURE_MIN = -3
BIOME_TEMPERATURE_MAX = 3
BIOME_TREES_LEN_MIN = 0
BIOME_TREES_LEN_MAX = 32

# Pour Color:
COLOR_RGB_MIN = 0
COLOR_RGB_MAX = 255

# Pour Seed:
SEED_ELEMENT_MIN = - 10000
SEED_ELEMENT_MAX = 10000

